# Generated by Django 5.1.7 on 2025-04-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
    ]
