# Generated by Django 5.1.7 on 2025-04-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_faculty_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty_table',
        ),
    ]
