# Generated by Django 5.1.7 on 2025-04-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_attendance_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
